version: "3.8"

services:
  api:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
    # TODO If I change this to './main.go:/app/main.go' (so .dockerignore ignores the correct files)
    # then air live reloading won't work. Why?
      - ./:/app/
  db:
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local