version: "3.8"

services:
  api:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
    # TODO If I change this to './main.go:/app/main.go' (so .dockerignore ignores the correct files)
    # then air live reloading won't work. Why?
      - ./:/app/
  db:
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      timeout: 5s
      retries: 5
  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./internal/db/migrations:/migrations
    command:
      ["-path", "./migrations/", "-database",  "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB?sslmode=disable", "up"]

volumes:
  db-data:
    driver: local